Added documentation
saltastroops/data-archive-backend pull request #132
Opened 2020-04-17 13:59 UTC by chynamyerz

2020-05-07 15:54 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: all files reviewed, 23 unresolved discussions (waiting on @chynamyerz)

___
*[README.md, line 13 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6j_cx-C43srmAHEhQB:-M6j_cx-C43srmAHEhQC:br7sczm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L13)):*
> ```Markdown
> ## Setting up
> 
> Assuming that you have followed the instructions outlined in the file ```sever_setup.md``` found in the ```docs``` directory you may proceed, if not, please start by following it first.
> ```

Before proceeding you need to have set up a server as described in [docs/server_setup.md](docs/server_setup.md).
___
*[README.md, line 63 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6j_Tzd6LELvNieqDdb:-M6j_Tzd6LELvNieqDdc:b-ydo40e) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L63)):*
> ```Markdown
> These must be defined in a file ```.env``` in the root directory. *This file should not be committed to the git repository.*
> 
> The SDB information can only be requested from the Astroops Software line manager at SALT.
> ```

I'm not sure this sentence is necessary.
___
*[README.md, line 68 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jaHQ093lzCciB4h2y:-M6jaHQ093lzCciB4h2z:bgo36i7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L68)):*
> ```Markdown
> 
> The `TZ` variable needs to be set to ensure that Node and the PostgreSQL driver use UTC when converting `DATE` database entries to a JavaScript `Date` object.
> ```

Add: The `SSDA_DATABASE_USER` should have the `admin_editor` and `archive_user` roles in the SSDA database.

Add: The `SDB_DATABASE_USER` should have SELECT permissions for the tables in the SDB.
___
*[README.md, line 94 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jayKp-m1B1xmA5csH:-M6jayKp-m1B1xmA5csI:bulueop) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L94)):*
> ```Markdown
> ```
> 
> To run the tests, executes the usual npm test command,
> ```

npm ---> yarn
___
*[docs/ci_cd.md, line 5 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jc1q48lV1eQsrnfGI:-M6jc1q5-OD6hqGkfqlZ:be1d2e9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L5)):*
> ```Markdown
> In favor of employing Continuous Integration and Continuous Deployment, GitHub Actions feature is used to achieved this.
> 
> Continuous Integration is the process of building your application continuously in bits and pieces. It involves code compilation and validation, code review, testing and packaging your application ready for release.
> ```

I'd rather not include the general statements. Instead you may just provide links. (Or say what this project is doing.)

In favor --> In order to
___
*[docs/ci_cd.md, line 11 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jdesyDHTURFgqZq6t:-M6jdesyDHTURFgqZq6u:bq3yn4m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L11)):*
> ```Markdown
> # GitHub Actions
> 
> It is a new GitHub feature used to automate your workflow from software development to production.
> ```

Avoid the word "new". And again I'd avoid the general "praise".
___
*[docs/ci_cd.md, line 17 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jdw_jEuZvwW2AzcDH:-M6jdw_jEuZvwW2AzcDI:bz8n5tt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L17)):*
> ```Markdown
> ## GitHub Actions Execution
> 
> To execute GitHub Actions, you must define a workflow.
> ```

Rather than phrasing this generally, you should refer to this project.
___
*[docs/ci_cd.md, line 25 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jeLFI6aKn-PSVIoik:-M6jeLFI6aKn-PSVIoil:bwtkihi) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L25)):*
> ```Markdown
> In order for GitHub to know about any defined workflow, in your repository root directory, there must be a .github/workflow/ directory.
> 
> Inside the workflow/ directory you may define *.yml or *.yaml files, which are the actual workflow configuration files.
> ```

`*.yaml ---> *.yaml*`
___
*[docs/ci_cd.md, line 30 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jeaJnD_OQ5wbgSJP6:-M6jeaJnD_OQ5wbgSJP7:buk6eye) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L30)):*
> ```Markdown
> 
> ## Workflows
> In order to reach the development or production server and actually deploy the updated version of the Data Archive API we should set gitHub secret vairables for connecting to the development server.
> ```

For consistency, maybe use "you" instead of "we".

gitHub ---> GitHub (or just leave it out)

secret vairables ---> `[secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)
___
*[docs/ci_cd.md, line 39 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jghidD0oHJ3IuiZ7k:-M6jghidD0oHJ3IuiZ7l:bpxofrd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L39)):*
> ```Markdown
> SSH_MACHINE_USER | The ssh server user | ssda
> SSH_MACHINE_PORT | The ssh server port | 22 
> ```

Add: The secrets can be set by the project owner in the project settings.
___
*[docs/ci_cd.md, line 42 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jh4PmC6M1NE7DYnyN:-M6jh4PnE3T_aqlBZXst:b4ax9pq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L42)):*
> ```Markdown
> ####  The Data Archive API Features Workflow
> 
> Create a file ```feature.yml``` inside the ```.github/worflows``` directory and add the content below to it.
> ```

You should just state what workflows are defined and where to find them. I don;t think there is a need to include the file contents. :)
___
*[docs/server_setup.md, line 3 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6ji_lGCjejOP8IC_M7:-M6ji_lGCjejOP8IC_M8:bw142nf) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L3)):*
> ```Markdown
> # SALT/SAAO Data Archive API Server Setup
> 
> The SALT/SAAO Data Archive API is hosted on the Ubuntu 16.04 server.
> ```

Probably: 16.04 or higher
___
*[docs/server_setup.md, line 9 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jie298lKfXaxmgEUJ:-M6jie298lKfXaxmgEUK:b5zw752) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L9)):*
> ```Markdown
> ## Install Node JS Using a PPA
> 
> This will allow you to install the latest [NodeJS](https://nodejs.org/en/) or may choose the version of node.js you want to install. By the time of writing this document, version 12.16.2 was the latest.
> ```

At the moment, Node 14 is the latest version - and it doesn't work. So maybe ask for Node 12?
___
*[docs/server_setup.md, line 29 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jjH6s1KyqCpAv9xMx:-M6jjH6s1KyqCpAv9xMy:bm4wvms) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4 [...]

2020-05-07 16:01 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: all files reviewed, 24 unresolved discussions (waiting on @chynamyerz)

___
*[docs/server_setup.md, line 37 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jrXSD1cWPVpBt8gXS:-M6jrXSD1cWPVpBt8gXT:b-ch0htu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L37)):*
> ```Markdown
> 
> The nodejs package contains the nodejs binary as well as npm, so you don't need to install npm separately.
> ```

You  might need to include some instructions for bcrypt. (Ask Nhlavu.)


<!-- Sent from Reviewable.io -->

2020-05-08 10:25 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 1 of 4 files reviewed, 24 unresolved discussions (waiting on @hettlage)

___
*[README.md, line 13 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6j_cx-C43srmAHEhQB:-M6nXxA1BPT8lFtPNUXm:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Before proceeding you need to have set up a server as described in [docs/server_setup.md](docs/server_setup.md).
</blockquote></details>

Done.
___
*[README.md, line 63 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6j_Tzd6LELvNieqDdb:-M6nXyD65S7WHunQbdMC:b-hfpv0l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure this sentence is necessary.
</blockquote></details>

removed
___
*[README.md, line 68 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jaHQ093lzCciB4h2y:-M6nXzfc3AEZRLsQv_hO:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Add: The `SSDA_DATABASE_USER` should have the `admin_editor` and `archive_user` roles in the SSDA database.

Add: The `SDB_DATABASE_USER` should have SELECT permissions for the tables in the SDB.
</blockquote></details>

Added
___
*[README.md, line 94 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jayKp-m1B1xmA5csH:-M6nY9Ud1WK285s-rV2X:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

npm ---> yarn
</blockquote></details>

Done.
___
*[docs/ci_cd.md, line 5 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jc1q48lV1eQsrnfGI:-M6no4QTAyx0hrib1wkK:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather not include the general statements. Instead you may just provide links. (Or say what this project is doing.)

In favor --> In order to
</blockquote></details>

Done.
___
*[docs/ci_cd.md, line 11 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jdesyDHTURFgqZq6t:-M6no3rk2VHObQZ6S17d:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Avoid the word "new". And again I'd avoid the general "praise".
</blockquote></details>

Done.
___
*[docs/ci_cd.md, line 17 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jdw_jEuZvwW2AzcDH:-M6no3Lc8D2CXzo9AqKn:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather than phrasing this generally, you should refer to this project.
</blockquote></details>

Done.
___
*[docs/ci_cd.md, line 25 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jeLFI6aKn-PSVIoik:-M6no-yj1ibfKEy_ezAi:b-hfpv0l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`*.yaml ---> *.yaml*`
</blockquote></details>

removed
___
*[docs/ci_cd.md, line 30 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jeaJnD_OQ5wbgSJP6:-M6no-G8BZ7iPqyPtk9-:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency, maybe use "you" instead of "we".

gitHub ---> GitHub (or just leave it out)

secret vairables ---> `[secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)
</blockquote></details>

Done.
___
*[docs/ci_cd.md, line 39 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jghidD0oHJ3IuiZ7k:-M6nnzi-ASGoCKRh0C6H:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Add: The secrets can be set by the project owner in the project settings.
</blockquote></details>

Done.
___
*[docs/ci_cd.md, line 42 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jh4PmC6M1NE7DYnyN:-M6nnzAD-mEF2mYohoo6:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should just state what workflows are defined and where to find them. I don;t think there is a need to include the file contents. :)
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 3 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6ji_lGCjejOP8IC_M7:-M6nnyIiEXCW2bvoIcn9:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably: 16.04 or higher
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 9 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jie298lKfXaxmgEUJ:-M6nnxpb6Vi3nqjAfJzQ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

At the moment, Node 14 is the latest version - and it doesn't work. So maybe ask for Node 12?
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 29 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jjH6s1KyqCpAv9xMx:-M6nnxME6eJrumQrLYpI:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here and everywhere else I'm not sure you need to include the output.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 36 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jjVKCAW_-xQ5w-M8i:-M6nnwom8vl5WoGjQQ4I:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The nodejs package contains the nodejs binary as well as npm. To check that it is installed, you can run ...

However, given that project is using yarn, you shouldn't even mention this, and you should not say that yarn is optional.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 37 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jrXSD1cWPVpBt8gXS:-M6nnw8I9EeX2HZ0LVjW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L37)):*
<details><summary><i>Previously, [...]

2020-05-08 18:06 UTC, hettlage requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 2 of 4 files reviewed, 17 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[README.md, line 13 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6j_cx-C43srmAHEhQB:-M6oS_Mt6W8v7SaHShXc:bgq9qxl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/README.md#L13)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should use a relative link (`[docs/server_setup.md](docs/server_setup.md)`).
___
*[README.md, line 63 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6oSzEv6t4sg7TPcAKr:-M6oSzEv6t4sg7TPcAKs:bpp33u3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f7510385698ae188d9fa4dd1123bdcd796a0b4db/README.md#L63)):*
> ```Markdown
> These must be defined in a file ```.env``` in the root directory. *This file should not be committed to the git repository.*
> 
> The SSDA information should match the PostgreSQL information you installed and set up.
> ```

That ("should match the PostgreSQL information you installed") sounds strange. I think you can omit it.
___
*[docs/ci_cd.md, line 1 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6pS1roELSX7eESPLJj:-M6pS1roELSX7eESPLJk:b-65t1xq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L1)):*
> ```Markdown
> # Delivery and Deployment
> ```

Here is my suggestion:

```
# Delivery and Deployment

[GitHub Actions](https://github.com/features/actions) are used for Continuous Integration and Continuous Deployment. The [workflows](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-and-managing-workflow-files-and-runs) are listed below.

## Secrets
To allow the deployment of an updated version of the Data Archive backend to the development or production server, you have to set secrets for connecting to the server.

```TODO UPDATE Differentiate betwen dev and live ssh machines```
Variable | Description | Example
---- | ---- | ----
SSH_MACHINE_PRIVATE_SSH_KEY | The ssh server private key | secret key
SSH_MACHINE_HOST | The ssh server host | http://localhost
SSH_MACHINE_USER | The ssh server user | ssda
SSH_MACHINE_PORT | The ssh server port | 22 

The secrets can be set by the project owner in the project settings.

## Features Workflow

The features workflow is triggered whenever there is a new branch added or there are new commits pushed to that branch. This excludes the master and the development branch.

This workflow is defined in [github/workflows/features.yml](.github/workflows/features.yml).

## Development Workflow

The development workflow is triggered whenever there are new commits pushed to the development branch.

This workflow is defined in [github/workflows/development.yml](.github/workflows/features.yml).

### Master Workflow

The master workflow is triggered whenever there are new commits pushed to the master branch.

This workflow is defined in [github/workflows/master.yml](.github/workflows/features.yml).
```


<!-- Sent from Reviewable.io -->

2020-05-11 08:06 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 1 of 4 files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[README.md, line 63 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6oSzEv6t4sg7TPcAKr:-M71koebAy0BDiekfkdO:bxe89cd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f7510385698ae188d9fa4dd1123bdcd796a0b4db/README.md#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That ("should match the PostgreSQL information you installed") sounds strange. I think you can omit it.
</blockquote></details>

Omited
___
*[docs/ci_cd.md, line 1 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6pS1roELSX7eESPLJj:-M71krzu2qD11rB28Mhc:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/ci_cd.md#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here is my suggestion:

```
# Delivery and Deployment

[GitHub Actions](https://github.com/features/actions) are used for Continuous Integration and Continuous Deployment. The [workflows](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-and-managing-workflow-files-and-runs) are listed below.

## Secrets
To allow the deployment of an updated version of the Data Archive backend to the development or production server, you have to set secrets for connecting to the server.

```TODO UPDATE Differentiate betwen dev and live ssh machines```
Variable | Description | Example
---- | ---- | ----
SSH_MACHINE_PRIVATE_SSH_KEY | The ssh server private key | secret key
SSH_MACHINE_HOST | The ssh server host | http://localhost
SSH_MACHINE_USER | The ssh server user | ssda
SSH_MACHINE_PORT | The ssh server port | 22 

The secrets can be set by the project owner in the project settings.

## Features Workflow

The features workflow is triggered whenever there is a new branch added or there are new commits pushed to that branch. This excludes the master and the development branch.

This workflow is defined in [github/workflows/features.yml](.github/workflows/features.yml).

## Development Workflow

The development workflow is triggered whenever there are new commits pushed to the development branch.

This workflow is defined in [github/workflows/development.yml](.github/workflows/features.yml).

### Master Workflow

The master workflow is triggered whenever there are new commits pushed to the master branch.

This workflow is defined in [github/workflows/master.yml](.github/workflows/features.yml).
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-11 19:18 UTC, hettlage requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: all files reviewed, 12 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[docs/ci_cd.md, line 28 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sD0w7lf6fTQoQBES:-M73sD0w7lf6fTQoQBET:bjza496) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/ci_cd.md#L28)):*
> ```Markdown
> The development workflow is triggered whenever there are new commits pushed to the development branch.
> 
> This workflow is defined in [github/workflows/development.yml](.github/workflows/features.yml).
> ```

features ---> development
___
*[docs/ci_cd.md, line 34 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sHsi43asPUnJ6UWH:-M73sHsi43asPUnJ6UWI:bjpf8s3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/ci_cd.md#L34)):*
> ```Markdown
> The master workflow is triggered whenever there are new commits pushed to the master branch.
> 
> This workflow is defined in [github/workflows/master.yml](.github/workflows/features.yml).
> ```

features ---> master
___
*[docs/server_setup.md, line 190 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M6jnUHz3XJJ8_9U3McS:-M747te96ygjIALs-OUN:bcwg6f0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/d933d6092c7a2a4dcbfeea2694adcb66190cd475/docs/server_setup.md#L190)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

in the server ---> on the server
___
*[docs/server_setup.md, line 3 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sNTS7X5Ju2YqwPZs:-M73sNTS7X5Ju2YqwPZt:b2a6in6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L3)):*
> ```Markdown
> # SALT/SAAO Data Archive API Server Setup
> 
> The SALT/SAAO Data Archive API is hosted on the Ubuntu 16.04 or higher server.
> ```

is --> should be

the Ubuntu 16.04 or higher server ---> on a server running under Ubuntu 16.04 or higher.
___
*[docs/server_setup.md, line 52 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73u0fu4M1gnoofqF0p:-M73u0fu4M1gnoofqF0q:b-x35le4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L52)):*
> ```Markdown
> 
> ```sh
> sudo apt-get install -y build-essential python
> ```

I don't think you should include the -y option.

Judging from https://stackoverflow.com/questions/25848475/unable-to-install-npm-bcrypt-on-ubuntu you only need

```sudo apt install build-essential```
___
*[docs/server_setup.md, line 57 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73ulPtBXmZwtgIHukd:-M73ulPtBXmZwtgIHuke:b-1szbh4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L57)):*
> ```Markdown
> ## Install Git
> 
> [Git](https://git-scm.com/) is an open source distributed dersion control system.
> ```

dersion ---> version
___
*[docs/server_setup.md, line 87 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M746sv_DMN95Rjg8-C3:-M746sv_DMN95Rjg8-C4:b-6tb2tu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L87)):*
> ```Markdown
> ```
> 
> ### Setup Nginx
> ```

Here is my suggestion for this section.

### Configuring Nginx

After installing Nginx you should add your server configuration in a file (`your.domain.conf`, say) in the folder `/etc/nginx/sites-available`. Afterwards you need to create a symbolic link in the folder `/etc/nginx/sites-enabled` which points to your configuration file. For example:

```sh
cd /etc/nginx/sites-enabled
ln -s /etc/nginx/sites-available/your.domain.conf your.domain.conf
```

The content of the configuration file depends on your particular needs. If the Data Archive backend is the only webservice running on the server, it might look as follows.

```conf
server {
  listen 80;
  server_name your_domain.com;
  location / {
    proxy_pass http://localhost:4000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
   }
}
```

If you are running both the Data Archive frontend and backend on the same server, it could look as follows.

```conf
server {
    listen 80 default_server;
    server_name your.domain;

    location / {
        root /var/www/frontend/build;
        index index.html index.htm;
        try_files $uri /index.html;
    }

    location /api {
        proxy_pass http://localhost:4000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
```

This setup assumes that all backend URLs are relative to `/api`. Note the slash at the end of `proxy_pass http://localhost:4001/`. This absolutely crucial, as otherwise Nginx won't drop the `/api` prefix when passing through requests.

To support HTTPS you must add the lines below inside the server block.

```conf
server {
  ...
  listen              443 ssl;
  ssl_certificate     /etc/nginx/cert.crt;
  ssl_certificate_key /etc/nginx/cert.key;
  ...
}
```

You will need to restart Nginx.

```sh
# To verify nginx configuration
sudo nginx -t

# Restart nginx
sudo service nginx restart
``
```

___
*[docs/server_setup.md, line 136 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M747gLA29U0GYRuS9Vr:-M747gLA29U0GYRuS9Vs:b-rb3zzc) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L136)):*
> ```Markdown
> 
> ### Setup the UFW
> You might face firewall issues, below is one solution but you may require further steps.
> ```

issues, below ---> issues. Below
___
*[docs/server_setup.md, line 166 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M748Isn7yZ8dx8X9T-F:-M748Isn7yZ8dx8X9T-G:b-dqv6qs) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L166)):*
> ```Markdown
> In production, you should use a daemon process. For Node.js you can use [PM2](http://pm2.keymetrics.io/) to set this up.
> 
> Install PM2 globally in the server.
> ```

You sometimes uses "PM2" and at other times "pm2".
___
*[docs/server_setup.md, line 178 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M748Tyd7AV6nkOqENwd:-M748Tyd7AV6nkOqENwe:bj4at4t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L178)):*
> ```Markdown
> ```
> 
> To run the Data Archive API with pm2, you should clone this repository first and run yarn start. 
> ```

Maybe add the commands for this?
___
*[docs/server_setup.md, line 180 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M748jA47_PQlldgec7E:-M748jA47_PQlldgec7F:bk4oykn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L180)):*
> ```Markdown
> To run the Data Archive API with pm2, you should clone this repository first and run yarn start. 
> 
> Restarting PM2 with the processes you manage on server boot/reboot is critical. To solve this, you should run pm2 startup after the Data Archive API is started and is running to generate an active startup script.
> ```

To ensure that pm2 restarts your process after a server reboot and automatically respawns the process, execute the following commands after sta [...]

2020-05-12 08:09 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[docs/ci_cd.md, line 28 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sD0w7lf6fTQoQBES:-M76pzTK1l7kYe_Oqvz5:b-zcjvte) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/ci_cd.md#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

features ---> development
</blockquote></details>

Thanks
___
*[docs/ci_cd.md, line 34 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sHsi43asPUnJ6UWH:-M76puYj4qcEK-GS-XA9:b-zcjvte) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/ci_cd.md#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

features ---> master
</blockquote></details>

Thanks
___
*[docs/server_setup.md, line 3 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sNTS7X5Ju2YqwPZs:-M76uYQk5Z19v0DgTIm9:bsitw26) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

is --> should be

the Ubuntu 16.04 or higher server ---> on a server running under Ubuntu 16.04 or higher.
</blockquote></details>

Edited
___
*[docs/server_setup.md, line 52 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73u0fu4M1gnoofqF0p:-M76uZt58FIsApmRqfVT:b-9755fa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should include the -y option.

Judging from https://stackoverflow.com/questions/25848475/unable-to-install-npm-bcrypt-on-ubuntu you only need

```sudo apt install build-essential```
</blockquote></details>

Thank you.
___
*[docs/server_setup.md, line 57 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73ulPtBXmZwtgIHukd:-M76ud9z7kKcQMBdHpag:bvs55d0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

dersion ---> version
</blockquote></details>

Thank you
___
*[docs/server_setup.md, line 87 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M746sv_DMN95Rjg8-C3:-M76rvQp9rvBYbn4RDRV:bw5vvis) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L87)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here is my suggestion for this section.

### Configuring Nginx

After installing Nginx you should add your server configuration in a file (`your.domain.conf`, say) in the folder `/etc/nginx/sites-available`. Afterwards you need to create a symbolic link in the folder `/etc/nginx/sites-enabled` which points to your configuration file. For example:

```sh
cd /etc/nginx/sites-enabled
ln -s /etc/nginx/sites-available/your.domain.conf your.domain.conf
```

The content of the configuration file depends on your particular needs. If the Data Archive backend is the only webservice running on the server, it might look as follows.

```conf
server {
  listen 80;
  server_name your_domain.com;
  location / {
    proxy_pass http://localhost:4000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
   }
}
```

If you are running both the Data Archive frontend and backend on the same server, it could look as follows.

```conf
server {
    listen 80 default_server;
    server_name your.domain;

    location / {
        root /var/www/frontend/build;
        index index.html index.htm;
        try_files $uri /index.html;
    }

    location /api {
        proxy_pass http://localhost:4000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
```

This setup assumes that all backend URLs are relative to `/api`. Note the slash at the end of `proxy_pass http://localhost:4001/`. This absolutely crucial, as otherwise Nginx won't drop the `/api` prefix when passing through requests.

To support HTTPS you must add the lines below inside the server block.

```conf
server {
  ...
  listen              443 ssl;
  ssl_certificate     /etc/nginx/cert.crt;
  ssl_certificate_key /etc/nginx/cert.key;
  ...
}
```

You will need to restart Nginx.

```sh
# To verify nginx configuration
sudo nginx -t

# Restart nginx
sudo service nginx restart
``

</blockquote></details>

Added, thank you.
___
*[docs/server_setup.md, line 136 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M747gLA29U0GYRuS9Vr:-M76sJTdCDWNC_3C2HgB:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L136)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

issues, below ---> issues. Below
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 166 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M748Isn7yZ8dx8X9T-F:-M76sl6t7ah1a5Aj46WL:bp47qqr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L166)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You sometimes uses "PM2" and at other times "pm2".
</blockquote></details>

should be PM2 for doc, and pm2 for commands. thanks
___
*[docs/server_setup.md, line 178 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M748Tyd7AV6nkOqENwd:-M76uVknCnnXsc_nGJmm:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L178)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add the commands for this?
</blockquote></details>

Added
___
*[docs/server_setup.md, line 180 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M748jA47_PQlldgec7E:-M76uSzO-M1_9rilmPVn:bsitw26) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L180)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

To ensure that pm2 restarts your process after a server reboot and automatically respawns the process, execute the following commands after starting the server with `yarn start`.

```sh
# generate an active startup script
pm2 startup

# freeze the process list for automatic respawn
pm2 save
```
</blockquote></details>

Edited


<!-- Sent from Reviewable.io -->

2020-05-12 09:19 UTC, hettlage requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 3 of 4 files reviewed, 25 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[docs/server_setup.md, line 3 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sNTS7X5Ju2YqwPZs:-M76wqQ-5l0_EbnQqZIg:b-s2bv8r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L3)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Edited
</blockquote></details>

Agh  man, I know I'm stubborn, but I still think you should say the API *should be* hosted. :)
___
*[docs/server_setup.md, line 4 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76zOUJ7SEqqmNDj5pz:-M76zOUJ7SEqqmNDj5q-:b-b5kuey) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L4)):*
> ```Markdown
> 
> The SALT/SAAO Data Archive API is hosted on a server running under Ubuntu 16.04 or higher.
> Various packges which are required to be installed to get the Data Archive API server up and running.
> ```

Various packages need to be installed and configured to get the Data Archive API server up and running.
___
*[docs/server_setup.md, line 11 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77-SAs8lMUfiHyK7T3:-M77-SAs8lMUfiHyK7T4:b4vaidv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L11)):*
> ```Markdown
> [NodeJS](https://nodejs.org/en/) version 12.x should be installed.
> 
> ```sh
> ```

There is a bit of an inconsistency: In some places `sh` is used, in others `bash`.
___
*[docs/server_setup.md, line 12 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76ziVNBJr8b14lPq0v:-M76ziVNBJr8b14lPq0w:b97jnki) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L12)):*
> ```Markdown
> 
> ```sh
> cd ~
> ```

I wouldn't leave an empty line between the commands.
___
*[docs/server_setup.md, line 17 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76zutY0fu6aZCz5PJu:-M76zutY0fu6aZCz5PJv:b-70yqs4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L17)):*
> ```Markdown
> ```
> 
> The PPA will be added to your configuration and your local package cache will be updated automatically. Should be able to install the Node.js package by running the following commands.
> ```

PPA needs to explained (i.e. written out in full)
___
*[docs/server_setup.md, line 17 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77-8cS6cIv9ShhtCzf:-M77-8cS6cIv9ShhtCzg:b-i0xnir) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L17)):*
> ```Markdown
> ```
> 
> The PPA will be added to your configuration and your local package cache will be updated automatically. Should be able to install the Node.js package by running the following commands.
> ```

This will add the PPA ... and automatically update ...
___
*[docs/server_setup.md, line 17 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M7707J23QnvsWh-NEXq:-M7707J3C88BinTuD_wV:b-l23l3y) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L17)):*
> ```Markdown
> ```
> 
> The PPA will be added to your configuration and your local package cache will be updated automatically. Should be able to install the Node.js package by running the following commands.
> ```

Should be able ---> You should then be able
___
*[docs/server_setup.md, line 20 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76zp0S7QTOU2RRgYy1:-M76zp0S7QTOU2RRgYy2:b97jnki) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L20)):*
> ```Markdown
> 
> ```sh
> sudo apt-get update
> ```

I wouldn't leave an empty line between the commands.
___
*[docs/server_setup.md, line 31 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M770S6J9Ra5uSOXjRQF:-M770S6K1_exSITLwipT:bvdvlbh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L31)):*
> ```Markdown
> ```
> 
> Install [Yarn](https://classic.yarnpkg.com/en/) by executing the following commands
> ```

You use three different versions of yarn: "Yarn", "yarn" and "`yarn`". You should choose one. :)
___
*[docs/server_setup.md, line 39 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M770vDm6txp0bTvIr24:-M770vDm6txp0bTvIr25:b-dc5h2g) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L39)):*
> ```Markdown
> 
> ```sh
> sudo apt update && sudo apt install yarn
> ```

For consistency you shouldn't use `&&`.
___
*[docs/server_setup.md, line 47 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M7717V-APaOu7Th59Dm:-M7717V0Dge3rXpZp8f8:b-i4jsvn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L47)):*
> ```Markdown
> ```
> 
> The Data Archive API uses a [bcrypt](https://www.npmjs.com/package/bcrypt) package which is installed via `yarn` along other specified packages in the `package.json` file. For it to install successfuly, a python build essential should be installed first. 
> ```

a bcrypt package --> the bcrypt package
___
*[docs/server_setup.md, line 47 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M771O7g8eY2n1SdNLhp:-M771O7g8eY2n1SdNLhq:b-fgdmup) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L47)):*
> ```Markdown
> ```
> 
> The Data Archive API uses a [bcrypt](https://www.npmjs.com/package/bcrypt) package which is installed via `yarn` along other specified packages in the `package.json` file. For it to install successfuly, a python build essential should be installed first. 
> ```

For it to install successfuly, a python build essential should be installed first.

---> For it to install successfully, you might have to install the build-essential package first.
___
*[docs/server_setup.md, line 49 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M7728wpCV3J7f8H1c0c:-M7728wpCV3J7f8H1c0d:b-aroicq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L49)):*
> ```Markdown
> The Data Archive API uses a [bcrypt](https://www.npmjs.com/package/bcrypt) package which is installed via `yarn` along other specified packages in the `package.json` file. For it to install successfuly, a python build essential should be installed first. 
> 
> To install it run
> ```

This line is unnecessary, I think.
___
*[docs/server_setup.md, line 57 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M772TtU1a1HBkAkJqtA:-M772TtU1a1HBkAkJqtB:bqnx7ih) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L57)):*
> ```Markdown
> ## Install Git
> 
> [Git](https://git-scm.com/) is an open source distributed version control system.
> ```

Can be shortened:

[Git](https://git-scm.com/) can be installed by running
___
*[docs/server_setup.md, line 65 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M772kX_Buhu6VczLMCU:-M772kX_Buhu6VczLMCV:bf1kcq8) ([raw file](htt [...]

2020-05-12 10:10 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 2 of 4 files reviewed, 25 unresolved discussions (waiting on @hettlage)

___
*[docs/server_setup.md, line 3 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M73sNTS7X5Ju2YqwPZs:-M77EvLzD_bX_2to5DXd:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7aa48983a8043327cf01a2318569dcdaaf9695fe/docs/server_setup.md#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Agh  man, I know I'm stubborn, but I still think you should say the API *should be* hosted. :)
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 4 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76zOUJ7SEqqmNDj5pz:-M77F2q28o4nnqZqb1jm:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Various packages need to be installed and configured to get the Data Archive API server up and running.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 11 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77-SAs8lMUfiHyK7T3:-M77F5NC0OK6MxLD2udO:b7e7cpd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a bit of an inconsistency: In some places `sh` is used, in others `bash`.
</blockquote></details>

sticking to sh
___
*[docs/server_setup.md, line 12 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76ziVNBJr8b14lPq0v:-M77FB6NAVhjAbPYWr2-:b-hfpv0l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wouldn't leave an empty line between the commands.
</blockquote></details>

removed
___
*[docs/server_setup.md, line 17 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76zutY0fu6aZCz5PJu:-M77FaN79im55eTWXAAh:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

PPA needs to explained (i.e. written out in full)
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 17 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77-8cS6cIv9ShhtCzf:-M77G7HT-0J0HhDmCsvO:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This will add the PPA ... and automatically update ...
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 17 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M7707J23QnvsWh-NEXq:-M77G7b_9PxZftPoj99B:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be able ---> You should then be able
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 20 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M76zp0S7QTOU2RRgYy1:-M77LdmyEJYARUUmnR5o:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wouldn't leave an empty line between the commands.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 31 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M770S6J9Ra5uSOXjRQF:-M77GRx9EsWDCofIJS7q:bvvox90) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You use three different versions of yarn: "Yarn", "yarn" and "`yarn`". You should choose one. :)
</blockquote></details>

stick to yarn
___
*[docs/server_setup.md, line 39 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M770vDm6txp0bTvIr24:-M77Lfby0vwjeDGwSepG:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency you shouldn't use `&&`.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 47 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M7717V-APaOu7Th59Dm:-M77H2jA4LGk_o3qFSBu:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a bcrypt package --> the bcrypt package
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 47 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M771O7g8eY2n1SdNLhp:-M77HFp73H2gZiF6KkkP:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For it to install successfuly, a python build essential should be installed first.

---> For it to install successfully, you might have to install the build-essential package first.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 49 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M7728wpCV3J7f8H1c0c:-M77HIE46BkoI8KQyy0i:b-hfpv0l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line is unnecessary, I think.
</blockquote></details>

removed
___
*[docs/server_setup.md, line 57 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M772TtU1a1HBkAkJqtA:-M77HTa6C2tV734fjMzD:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be shortened:

[Git](https://git-scm.com/) can be installed by running
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 65 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M772kX_Buhu6VczLMCU:-M77HUNr70ECgkSL1KeV:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

successfuly ---> successfully
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 71 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M775yX2Bkq91NVbiw8i:-M77Ks1f4N2U5-Cpm-IA:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the sections should be rearranged:

- clone the repository
- install yarn and use it to install the packages
- install PM2 and set it up
- install and configure Nginx
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 73 at r4](http [...]

2020-05-12 12:11 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: all files reviewed, 20 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[docs/server_setup.md, line 39 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M770vDm6txp0bTvIr24:-M77kXMiB2DIq9V1Q7qn:b-1payc7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L39)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uhm, I don't think it has been done? :)
___
*[docs/server_setup.md, line 7 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77j1mjBhQnz1l0gBpz:-M77j1mjBhQnz1l0gBq-:b8afxoo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L7)):*
> ```Markdown
> 
> 
> ## Install Node JS using a Personal Package Archives (PPA)
> ```

Install NodeJS, yarn and bcrypt
___
*[docs/server_setup.md, line 16 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77jvtkBljUcAkILtyn:-M77jvtkBljUcAkILtyo:b5kkxxb) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L16)):*
> ```Markdown
> ```
> 
> This will add the PPA to your configuration and automatically update your local package cache. You should then be able to install the Node.js package by running the following commands.
> ```

This will add Node's Personal Package Archive to ...
___
*[docs/server_setup.md, line 80 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77iLi78RKipiukAgHe:-M77iLi78RKipiukAgHf:b-57eav7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L80)):*
> ```Markdown
> ```sh
> cd data-archive-backend
> yarn install
> ```

You might add a sentence like the following:

As mentioned above, you might have to install the build_essential package if the installation of bcrypt fails.
___
*[docs/server_setup.md, line 105 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77kjmH7E7jEvqcyF1d:-M77kjmH7E7jEvqcyF1e:b-h7v50z) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L105)):*
> ```Markdown
> ```
> 
> To ensure that PM2 restarts your process after a server reboot and automatically respawns the process, execute the following commands after starting the server.
> ```

Maybe add a sentence before "To ensure that...":

This command uses PM2 to launch the server.
___
*[docs/server_setup.md, line 108 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77lXJoAdpqqgjK0YUY:-M77lXJoAdpqqgjK0YUZ:bo3qupq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L108)):*
> ```Markdown
> 
> ```sh
> pm2 startup
> ```

```
# generate an active startup script
pm2 startup

# freeze the process list for automatic respawn
pm2 save
```
___
*[docs/server_setup.md, line 212 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77mAaM9JFJhQNuKS4_:-M77mAaM9JFJhQNuKS4a:by4p5hs) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L212)):*
> ```Markdown
> ```
> 
> Check the statu of UWF
> ```

statu ---> status

UWF ---> UFW
___
*[docs/server_setup.md, line 218 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77mOYW-BACe0bHY4-Y:-M77mOYW-BACe0bHY4-Z:ba0ve8d) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L218)):*
> ```Markdown
> ```
> 
> Check the available ufw application profiles
> ```

Yiu use UFW rather than ufw above.
___
*[docs/server_setup.md, line 224 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77mjiBBN9oHjQBHTj6:-M77mjiBBN9oHjQBHTj7:bvm4zm4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L224)):*
> ```Markdown
> ```
> 
> Allow and Deny (specific rules)
> ```

Deny ---> deny

Shouldn't there be an example for denying?


<!-- Sent from Reviewable.io -->

2020-05-12 12:38 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 3 of 4 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[docs/server_setup.md, line 39 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M770vDm6txp0bTvIr24:-M77qGWR1mR_fg6jj2EJ:b-bi6kpv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/62e5453ec05c073c76ce6dcf2d71747f73b39b25/docs/server_setup.md#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Uhm, I don't think it has been done? :)
</blockquote></details>

Now done.
___
*[docs/server_setup.md, line 7 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77j1mjBhQnz1l0gBpz:-M77sonI70vbsvacSr2r:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Install NodeJS, yarn and bcrypt
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 16 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77jvtkBljUcAkILtyn:-M77pxTN3uBk9rQ61bHp:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This will add Node's Personal Package Archive to ...
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 80 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77iLi78RKipiukAgHe:-M77r1TD3OGXnG0_MAj2:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might add a sentence like the following:

As mentioned above, you might have to install the build_essential package if the installation of bcrypt fails.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 105 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77kjmH7E7jEvqcyF1d:-M77rAE0EO0ete973s0U:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L105)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a sentence before "To ensure that...":

This command uses PM2 to launch the server.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 108 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77lXJoAdpqqgjK0YUY:-M77rJdj4qtB6OmSAlEo:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

```
# generate an active startup script
pm2 startup

# freeze the process list for automatic respawn
pm2 save
```
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 212 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77mAaM9JFJhQNuKS4_:-M77rTnU2Fu5fxCf1OX-:b-zcjvte) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L212)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

statu ---> status

UWF ---> UFW
</blockquote></details>

Thanks
___
*[docs/server_setup.md, line 218 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77mOYW-BACe0bHY4-Y:-M77rkrK2BGUcNN_WuPW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L218)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yiu use UFW rather than ufw above.
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 224 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77mjiBBN9oHjQBHTj6:-M77sXOU7IFr7c553_PM:b-j74fg2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/ecf7b6b0eb53c9683d1a315a922e60764e2570fc/docs/server_setup.md#L224)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Deny ---> deny

Shouldn't there be an example for denying?
</blockquote></details>

Same as allow, but added it


<!-- Sent from Reviewable.io -->

2020-05-12 12:53 UTC, hettlage requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: all files reviewed, 3 unresolved discussions (waiting on @chynamyerz)

___
*[docs/server_setup.md, line 16 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77tsFeC_Gizig5gBWz:-M77tsFeC_Gizig5gBX-:b-7h5gqk) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7c42e32a418eac7864b84384b152b04afed1ea31/docs/server_setup.md#L16)):*
> ```Markdown
> ```
> 
> This will add Node's Personal Package Archive to your configuration and automatically update your local package cache. You should then be able to install the Node.js package by running the following commands.
> ```

"configuration" might be a bit vague. How about:

This will add Node's Personal Package Archive to your system's software sources and ...
___
*[docs/server_setup.md, line 119 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77vPdcENNR6zYcwcDw:-M77vPey6e69Oh-EAvEK:bgtg7ll) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7c42e32a418eac7864b84384b152b04afed1ea31/docs/server_setup.md#L119)):*
> ```Markdown
> ```
> 
> To freeze a process list for automatic respawn run
> ```

Ah, sorry, it seems I was unclear. I meant to say that you should remove the sentence "To freeze a process list for automatic respawn run". And group the two commands together(*with the comments):

```
# generate an active startup script
pm2 startup

# freeze the process list for automatic respawn
pm2 save
```
___
*[docs/server_setup.md, line 241 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77wMzM5NvwHMID1FSV:-M77wMzM5NvwHMID1FSW:bwwtn0f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7c42e32a418eac7864b84384b152b04afed1ea31/docs/server_setup.md#L241)):*
> ```Markdown
> 
> ```sh
> sudo ufw deny <port>/<optional: protocol>
> ```

I'd put the two commands in the same code block.


<!-- Sent from Reviewable.io -->

2020-05-12 13:01 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[docs/server_setup.md, line 16 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77tsFeC_Gizig5gBWz:-M77xzdk-FKQD4IKVjOK:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7c42e32a418eac7864b84384b152b04afed1ea31/docs/server_setup.md#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"configuration" might be a bit vague. How about:

This will add Node's Personal Package Archive to your system's software sources and ...
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 119 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77vPdcENNR6zYcwcDw:-M77yCb41OjqMRXOJr7N:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7c42e32a418eac7864b84384b152b04afed1ea31/docs/server_setup.md#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, sorry, it seems I was unclear. I meant to say that you should remove the sentence "To freeze a process list for automatic respawn run". And group the two commands together(*with the comments):

```
# generate an active startup script
pm2 startup

# freeze the process list for automatic respawn
pm2 save
```
</blockquote></details>

Done.
___
*[docs/server_setup.md, line 241 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/132#-M77wMzM5NvwHMID1FSV:-M77xoCGCMH-2TP4WJLm:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7c42e32a418eac7864b84384b152b04afed1ea31/docs/server_setup.md#L241)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd put the two commands in the same code block.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-12 13:50 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/132)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-05-12 13:53 UTC, merged